### ISSUE TITLE
Complete login page template

### ISSUE THREAD

**Issue by BroFromSpace** [BroFromSpace/petico#1]
**Task Description: Create a Login Page with Nuxt.js**

**Objective**
Create a login page using Nuxt.js that allows users to sign in for your application. The login page should include input fields for email and password. Ensure that the form fields are validated using Vuelidate.

- [x] Create Login Page
- [x] Add input fields for email and password
- [x] Configure _[Vuelidate](https://vuelidate-next.netlify.app/)_ to work with login form
